services:
  - type: web
    name: task-manager-backend
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: task-manager-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://task-manager-backend.onrender.com 